version: 2
jobs:
  build:
    working_directory: /go/src/github.com/MSathieu/SimpleVCS/
    docker:
      - image: golang:1.9.1
    steps:
      - checkout
      - run: go get
      - run: go test ./...
